[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
markers =
    asyncio: async tests
    integration: integration tests
    slow: slow tests
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
